CREATE TABLE tbl_usuarios_py (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(10) NOT NULL,
    CONSTRAINT usuarios_pk PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_email_unique UNIQUE (email)
);


INSERT INTO tbl_usuarios_py (nome, email, senha) VALUES ('Vinícius Saes', 'vinicius@fiap.com.br', '1234');

COMMIT;